name: Prettier Check

on:
  pull_request:
    paths:
      - '**/*.{js,jsx,ts,tsx,json,css,scss,md,yaml,yml}'

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Check Prettier
        run: npx prettier --check .
